# Google Cloud Build 파이프라인 설정
steps:
  # 1단계: Docker 이미지 빌드
  # Dockerfile을 사용하여 애플리케이션을 컨테이너화하고,
  # Artifact Registry에 저장할 이미지 태그를 지정합니다. (리전/프로젝트ID/저장소이름/이미지이름:태그)
  # $_SERVICE_NAME, $SHORT_SHA 값은 Cloud Build가 자동으로 제공하는 변수입니다.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
      - '.'
    id: 'Build'

  # 2단계: Docker 이미지 Artifact Registry에 푸시
  # 빌드된 이미지를 저장소로 푸시합니다.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
    id: 'Push'

  # 3단계: Cloud Run에 배포
  # gcloud sdk를 사용하여 새로운 이미지로 Cloud Run 서비스를 배포(또는 업데이트)합니다.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' # 배포할 Cloud Run 서비스 이름
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--quiet'
      # --allow-unauthenticated: 인증 없이 누구나 접근 가능한 웹 서비스로 설정
      - '--allow-unauthenticated'
      # 서비스에 환경 변수 설정
      # GCS_BUCKET_NAME: 애플리케이션이 사용할 GCS 버킷 이름
      # GOOGLE_API_KEY: Gemini API 키 (실제 운영 환경에서는 Secret Manager 사용을 권장)
      - '--set-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},GOOGLE_API_KEY=${_GOOGLE_API_KEY}'
      # Cloud Run 서비스가 사용할 메모리 및 CPU 설정
      - '--memory=4Gi'
      - '--cpu=2'
      # 동시 요청 수 설정. Streamlit은 단일 사용자 세션 기반이므로 낮게 설정합니다.
      - '--concurrency=8'
      # 요청 타임아웃. LLM 응답, 데이터 처리 등이 길어질 수 있으므로 넉넉하게 설정합니다.
      - '--timeout=600'
    id: 'Deploy'

# 빌드 성공 후 Artifact Registry에 저장될 최종 이미지 목록
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'

# 기본 타임아웃 설정 (10분)
timeout: 600s
